### ISSUE TITLE
K3S Cluster Became Unstable During Operator Installation

### ISSUE THREAD

**Issue by benr** [mondoohq/mondoo-operator#137]
**Describe the bug**
When installing the Mondoo Operator via Kubectl I experienced several problems which may or may not be related, first on installation:

```
root@cuddletech-v3:~# kubectl apply -f https://github.com/mondoohq/mondoo-operator/releases/download/v0.0.10/mondoo-operator-manifests.yaml
Unable to connect to the server: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
So I tried downloading and applying locally to avoid a problem downloading:

```
root@cuddletech-v3:~/mondoo# curl -sSL https://github.com/mondoohq/mondoo-operator/releases/latest/download/mondoo-operator-manifests.yaml > mondoo-operator-manifests.yaml
root@cuddletech-v3:~/mondoo# kubectl apply -f mondoo-operator-manifests.yaml
Unable to connect to the server: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Running again in verbose:

```
root@cuddletech-v3:~/mondoo# kubectl -v=9 apply -f mondoo-operator-manifests.yaml
I0301 02:07:31.184180 2768656 loader.go:372] Config loaded from file:  /etc/rancher/k3s/k3s.yaml
I0301 02:07:31.538125 2768656 round_trippers.go:435] curl -k -v -XGET  -H "Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf" -H "User-Agent: kubectl/v1.21.7+k3s1 (linux/amd64) kubernetes/ac70570" 'https://127.0.0.1:6443/openapi/v2?timeout=32s'
I0301 02:07:41.631190 2768656 round_trippers.go:454] GET https://127.0.0.1:6443/openapi/v2?timeout=32s  in 10078 milliseconds
I0301 02:07:41.638670 2768656 round_trippers.go:460] Response Headers:
I0301 02:07:41.873633 2768656 helpers.go:234] Connection error: Get https://127.0.0.1:6443/openapi/v2?timeout=32s: net/http: TLS handshake timeout
F0301 02:07:41.888272 2768656 helpers.go:115] Unable to connect to the server: net/http: TLS handshake timeout
goroutine 1 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc000b8dee0, 0x6f, 0xc8)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x7cdde60, 0xc000000003, 0x0, 0x0, 0xc0008f0310, 0x2, 0x64edaee, 0xa, 0x73, 0x40fb00)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x7cdde60, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc0008714a0, 0x1, 0x1)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:735 +0x185
github.com/rancher/k3s/vendor/k8s.io/klog/v2.FatalDepth(...)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1500
github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0xc000923700, 0x40, 0x1)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x288
github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x5411560, 0xc000ab9980, 0x4e8bae8)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x935
github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/apply.NewCmdApply.func1(0xc001194000, 0xc0005ea900, 0x0, 0x3)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/apply/apply.go:177 +0x73
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc001194000, 0xc0005ea780, 0x3, 0x3, 0xc001194000, 0xc0005ea780)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00001b340, 0xc0000be1e0, 0xc0002847d0, 0x5)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:895
github.com/rancher/k3s/pkg/kubectl.main()
        /go/src/github.com/rancher/k3s/pkg/kubectl/main.go:47 +0x21d
github.com/rancher/k3s/pkg/kubectl.Main()
        /go/src/github.com/rancher/k3s/pkg/kubectl/main.go:30 +0x47
github.com/rancher/k3s/vendor/github.com/docker/docker/pkg/reexec.Init(...)
        /go/src/github.com/rancher/k3s/vendor/github.com/docker/docker/pkg/reexec/reexec.go:26
main.main()
        /go/src/github.com/rancher/k3s/cmd/server/main.go:34 +0xad1

goroutine 6 [chan receive]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x7cdde60)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by github.com/rancher/k3s/vendor/k8s.io/klog/v2.init.0
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:420 +0xdf

goroutine 129 [chan receive]:
github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc001130168)
        /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3ac
created by github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil.NewMergeLogger
        /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x85

goroutine 184 [select]:
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4e8b7b0, 0x540c1c0, 0xc000932cf0, 0x1, 0xc0000c8660)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x118
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4e8b7b0, 0x12a05f200, 0x0, 0x1, 0xc0000c8660)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x4e8b7b0, 0x12a05f200)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
created by github.com/rancher/k3s/vendor/k8s.io/component-base/logs.InitLogs
        /go/src/github.com/rancher/k3s/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a

goroutine 173 [chan receive]:
github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc001130e88)
        /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3ac
created by github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil.NewMergeLogger
        /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x85

goroutine 176 [chan receive]:
github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc001130fc0)
        /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3ac
created by github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil.NewMergeLogger
        /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x85

goroutine 195 [chan receive]:
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x7cddba0)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by github.com/rancher/k3s/vendor/k8s.io/klog.init.0
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:411 +0xd8

```
After several more attempts the load average of the node spiked above 22.0 and the system became very slow to respond, after which I rebooted the host.  Once it came up the installation succeeded without incident.  The symptoms suggest the problem may have been memory exhaustion, however the cluster had been up and running smoothly for several months prior to installation.

The host was a Digital Ocean VM with 4GB of RAM running Ubuntu 20.04 and K3S version v1.21.7+k3s1

**Comment by czunker** [comment]
The error messages look like `kubectl` couldn't connect to the API server.

I tried to reproduce this with:
Ubuntu 20.04
k3s version v1.23.8+k3s1 
mondoo-operator v0.5.1
but to no avail.

Load and memory on the VM were also fine.

@benr Do you want to give it another try, or should we close the issue?

**Comment by czunker** [comment]
To prevent this in the future: https://github.com/mondoohq/mondoo-operator/pull/481

**Comment by imilchev** [comment]
We now have tests with k3s running for every operator commit. I guess we can close this issue. @benr if you happen to encounter any issues again, feel free to re-open
