### ISSUE TITLE
Mondoo client Pods for node scans continuously restart

### ISSUE THREAD

**Issue by czunker** [mondoohq/mondoo-operator#155]
**Describe the bug**
The mondoo-client Pods doing the node scans continuously restart:
```
NAME                                                  READY   STATUS    RESTARTS          AGE
mondoo-client-cbc5g                                   1/1     Running   136 (56m ago)     5d17h
mondoo-client-cd84f967c-5bw5t                         1/1     Running   0                 5d16h
mondoo-client-cg7nl                                   1/1     Running   136 (47m ago)     5d16h
mondoo-client-f6vc7                                   1/1     Running   33 (49m ago)      29h
mondoo-client-qcqxb                                   1/1     Running   138 (8m22s ago)   5d17h
mondoo-client-r89sr                                   1/1     Running   137 (5m54s ago)   5d17h
mondoo-client-ssftt                                   1/1     Running   137 (60s ago)     5d17h
mondoo-client-tqhqq                                   1/1     Running   136 (45m ago)     5d16h
mondoo-operator-controller-manager-77dc49f869-6bmz7   2/2     Running   0                 5d16h
```

**To Reproduce**
1. Install operator 0.0.9
2. Wait some time (Seems to be the 2nd scan after an hour which crashes the Pod)
3. Inspect client Pods

**Expected behavior**
Pods should run without restart.

**Logs**
```
→ load inventory inventory=/etc/opt/mondoo/inventory.yml
→ Mondoo 5.29.1 (Space: "//captain.api.mondoo.app/spaces/dazzling-golick-767384", Service Account: "***", Managed Client: "unset")
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source --config
→ start mondoo background service
→ scan interval is 60 minute(s)
→ start the vulnerability scan
→ load fs mountdir=/mnt/host
→ resolved assets resolved-assets=1
→ establish connection to asset ip-*** (unknown)
→ load fs mountdir=/mnt/host
→ run policies for asset asset=ip-***
→ send all results asset=ip-***
→ start the vulnerability scan
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x5c80fed]

goroutine 53 [running]:
go.mondoo.io/mondoo/motor/inventory/v1.(*Inventory).PreProcess(0xc001030340)
	/builds/mondoolabs/mondoo/motor/inventory/v1/inventory.go:97 +0x50d
go.mondoo.io/mondoo/motor/inventory.(*inventoryManager).loadInventory(0xc000af6000, 0xc001030340)
	/builds/mondoolabs/mondoo/motor/inventory/manager.go:98 +0x45
go.mondoo.io/mondoo/motor/inventory.WithInventory.func1(0xc001dd4d10)
	/builds/mondoolabs/mondoo/motor/inventory/manager.go:40 +0x49
go.mondoo.io/mondoo/motor/inventory.New({0xc001dd4e00, 0x1, 0x0})
	/builds/mondoolabs/mondoo/motor/inventory/manager.go:75 +0x6d
go.mondoo.io/mondoo/apps/mondoo/cmd.glob..func41.1()
	/builds/mondoolabs/mondoo/apps/mondoo/cmd/serve.go:189 +0x1a5
go.mondoo.io/mondoo/apps/mondoo/cmd/serve.BackgroundScan.func1(0xc000132180, 0x0)
	/builds/mondoolabs/mondoo/apps/mondoo/cmd/serve/background_scan_unix.go:48 +0x182
created by go.mondoo.io/mondoo/apps/mondoo/cmd/serve.BackgroundScan
	/builds/mondoolabs/mondoo/apps/mondoo/cmd/serve/background_scan_unix.go:31 +0x316
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Kubernetes 1.22.5
 - Operator Version 0.0.9
 - Mondoo Client 5.29.1

**Additional context**
In contrast, the client Pod running the Kubernetes scan, scans every hour without crashing:
```
→ load inventory inventory=/etc/opt/mondoo/inventory.yml
→ Mondoo 5.29.1 (Space: "//captain.api.mondoo.app/spaces/dazzling-golick-767384", Service Account: "***", Managed Client: "unset")
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source --config
→ start mondoo background service
→ scan interval is 60 minute(s)
→ start the vulnerability scan
W0304 17:29:16.698217       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
→ use cluster name from node name cluster-name=***.compute.internal
→ resolved assets resolved-assets=1
→ establish connection to asset K8S Cluster ***.compute.internal (api)
W0304 17:29:28.550351       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
→ run policies for asset asset="K8S Cluster ***.compute.internal"
→ send all results asset="K8S Cluster ***.compute.internal"
→ start the vulnerability scan
W0304 18:29:15.698434       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
→ use cluster name from node name cluster-name=***.compute.internal
→ resolved assets resolved-assets=1
→ establish connection to asset K8S Cluster ***.compute.internal (api)
W0304 18:29:23.529539       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
→ run policies for asset asset="K8S Cluster ***.compute.internal"
→ send all results asset="K8S Cluster ***.compute.internal"
→ start the vulnerability scan
W0304 19:29:15.699175       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
→ use cluster name from node name cluster-name=***.compute.internal
→ resolved assets resolved-assets=1
→ establish connection to asset K8S Cluster ***.compute.internal (api)
W0304 19:29:23.344665       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
→ run policies for asset asset="K8S Cluster ***.compute.internal"
→ send all results asset="K8S Cluster ***.compute.internal"
→ start the vulnerability scan
```

**Comment by chris-rock** [comment]
Thank you @czunker for reporting. We try to reproduce.

**Comment by chris-rock** [comment]
We released Mondoo Client 5.29.2 which fixes the issue. Would be great to know if that fixed your specific issue. 

The next release of the operator includes an auto-update for the Mondoo Client. Until then, make sure the latest image is updated to the newest Mondoo Client.

**Comment by czunker** [comment]
Sorry, seems like the 2nd run still crashed the client:
```
→ load inventory inventory=/etc/opt/mondoo/inventory.yml
→ Mondoo 5.29.2 (Space: "//captain.api.mondoo.app/spaces/dazzling-golick-767384", Service Account: "25bVQ5KSYuc8vFrGZFqLSwLZcKk", Managed Client: "unset")
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source --config
→ start mondoo background service
→ scan interval is 60 minute(s)
→ start the vulnerability scan
→ load fs mountdir=/mnt/host
→ resolved assets resolved-assets=1
→ establish connection to asset ip-172-31-134-120 (unknown)
→ load fs mountdir=/mnt/host
→ run policies for asset asset=ip-172-31-134-120
→ send all results asset=ip-172-31-134-120
→ start the vulnerability scan
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x578463d]

goroutine 66 [running]:
go.mondoo.io/mondoo/motor/inventory/v1.(*Inventory).PreProcess(0xc000fa2540)
	/builds/mondoolabs/mondoo/motor/inventory/v1/inventory.go:104 +0x6dd
go.mondoo.io/mondoo/motor/inventory.(*inventoryManager).loadInventory(0xc001c46000, 0xc000fa2540)
	/builds/mondoolabs/mondoo/motor/inventory/manager.go:98 +0x45
go.mondoo.io/mondoo/motor/inventory.WithInventory.func1(0xc000a67d10)
	/builds/mondoolabs/mondoo/motor/inventory/manager.go:40 +0x49
go.mondoo.io/mondoo/motor/inventory.New({0xc000a67e00, 0x1, 0x0})
	/builds/mondoolabs/mondoo/motor/inventory/manager.go:75 +0x6d
go.mondoo.io/mondoo/apps/mondoo/cmd.glob..func41.1()
	/builds/mondoolabs/mondoo/apps/mondoo/cmd/serve.go:189 +0x1a5
go.mondoo.io/mondoo/apps/mondoo/cmd/serve.BackgroundScan.func1(0xc000a39500, 0x0)
	/builds/mondoolabs/mondoo/apps/mondoo/cmd/serve/background_scan_unix.go:48 +0x182
created by go.mondoo.io/mondoo/apps/mondoo/cmd/serve.BackgroundScan
	/builds/mondoolabs/mondoo/apps/mondoo/cmd/serve/background_scan_unix.go:31 +0x316
```

**Comment by czunker** [comment]
No Node Client Pod without a restart the last 60 minutes:
```
NAME                                                  READY   STATUS    RESTARTS      AGE
mondoo-client-5q89q                                   1/1     Running   2 (25m ago)   145m
mondoo-client-cd84f967c-n49c6                         1/1     Running   0             8h
mondoo-client-dd5h6                                   1/1     Running   2 (25m ago)   145m
mondoo-client-dngvq                                   1/1     Running   2 (25m ago)   145m
mondoo-client-p4rw9                                   1/1     Running   2 (25m ago)   145m
mondoo-client-tchnm                                   1/1     Running   2 (25m ago)   145m
mondoo-client-x9mg5                                   1/1     Running   2 (25m ago)   145m
mondoo-client-zfg6d                                   1/1     Running   2 (25m ago)   145m
mondoo-operator-controller-manager-77dc49f869-pf66k   2/2     Running   0             8h

```

**Comment by chris-rock** [comment]
Thank you for testing @czunker. I could not reproduce it yet, since it work on all my k8s test environments. We'll have another look.

**Comment by chris-rock** [comment]
Can you share your MondooAuditConfig? I just want to make sure I am not missing anything.

**Comment by czunker** [comment]
This is the AuditConfig:
```
apiVersion: k8s.mondoo.com/v1alpha1
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator-system
spec:
  mondooSecretRef: mondoo-client
  nodes:
    enable: true
  workloads:
    enable: true
    serviceAccount: mondoo-operator-workload
status:
  pods:
  - mondoo-client-5q89q
  - mondoo-client-cd84f967c-n49c6
  - mondoo-client-dd5h6
  - mondoo-client-dngvq
  - mondoo-client-p4rw9
  - mondoo-client-tchnm
  - mondoo-client-x9mg5
  - mondoo-client-zfg6d
```

It's Copy&Paste from here: https://github.com/mondoohq/mondoo-operator/blob/main/docs/user-manual-kubectl.md#deployment-of-operator-using-manifests

Would any other info help? Debug logs? Cloud Platform? ...

**Comment by czunker** [comment]
I reproduced the crash on a freshly installed KinD Cluster:
```
→ load inventory inventory=/etc/opt/mondoo/inventory.yml
→ Mondoo 5.29.2 (Space: "//captain.api.mondoo.app/spaces/dazzling-golick-767384", Service Account: "26O6FvI1nlY6dqdfprrEnGIDUoJ", Managed Client: "unset")
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source --config
→ start mondoo background service
→ scan interval is 5 minute(s)
→ start the vulnerability scan
→ load fs mountdir=/mnt/host
→ resolved assets resolved-assets=1
→ establish connection to asset kind-control-plane (unknown)
→ load fs mountdir=/mnt/host
→ run policies for asset asset=kind-control-plane
→ send all results asset=kind-control-plane

→ start the vulnerability scan
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x578463d]

goroutine 51 [running]:
go.mondoo.io/mondoo/motor/inventory/v1.(*Inventory).PreProcess(0xc0003edfc0)
	/builds/mondoolabs/mondoo/motor/inventory/v1/inventory.go:104 +0x6dd
go.mondoo.io/mondoo/motor/inventory.(*inventoryManager).loadInventory(0xc001bba000, 0xc0003edfc0)
	/builds/mondoolabs/mondoo/motor/inventory/manager.go:98 +0x45
go.mondoo.io/mondoo/motor/inventory.WithInventory.func1(0xc001391d10)
	/builds/mondoolabs/mondoo/motor/inventory/manager.go:40 +0x49
go.mondoo.io/mondoo/motor/inventory.New({0xc001391e00, 0x1, 0x0})
	/builds/mondoolabs/mondoo/motor/inventory/manager.go:75 +0x6d
go.mondoo.io/mondoo/apps/mondoo/cmd.glob..func41.1()
	/builds/mondoolabs/mondoo/apps/mondoo/cmd/serve.go:189 +0x1a5
go.mondoo.io/mondoo/apps/mondoo/cmd/serve.BackgroundScan.func1(0xc000c4a000, 0x0)
	/builds/mondoolabs/mondoo/apps/mondoo/cmd/serve/background_scan_unix.go:48 +0x182
created by go.mondoo.io/mondoo/apps/mondoo/cmd/serve.BackgroundScan
	/builds/mondoolabs/mondoo/apps/mondoo/cmd/serve/background_scan_unix.go:31 +0x316

```

Steps to reproduce:
Install KinD version 0.12.0
This is the cluster config:
```
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
```
Create the cluster: `kind create cluster --config kind-config.yaml`

Installed the mondoo-operator following these steps:
https://github.com/mondoohq/mondoo-operator/blob/main/docs/user-manual-kubectl.md#deployment-of-operator-using-manifests

I only changed the DaemonSet to run the scan every 5 Minutes.
This results in the node Pods restarting every 5 Minutes:
```
NAME                                                  READY   STATUS    RESTARTS        AGE
mondoo-client-5b5cd6fbd9-qzqq5                        1/1     Running   0               11m
mondoo-client-mxp9k                                   1/1     Running   1 (3m59s ago)   9m3s
mondoo-client-q9kxl                                   1/1     Running   1               9m5s
mondoo-client-vpwkf                                   1/1     Running   1 (4m4s ago)    9m7s
mondoo-operator-controller-manager-59446cf9bb-79wrq   2/2     Running   0               20m
```

This is the MondooAuditConfig of the KinD Cluster:
```
apiVersion: k8s.mondoo.com/v1alpha1
kind: MondooAuditConfig
metadata:
  finalizers:
  - k8s.mondoo.com/delete
  name: mondoo-client
  namespace: mondoo-operator
spec:
  mondooSecretRef: mondoo-client
  nodes:
    enable: true
    image: {}
    resources: {}
  webhooks:
    certificateConfig: {}
    enable: false
  workloads:
    enable: true
    image: {}
    resources: {}
    serviceAccount: mondoo-operator-workload
status:
  pods:
  - mondoo-client-5b5cd6fbd9-qzqq5
  - mondoo-client-mxp9k
  - mondoo-client-q9kxl
  - mondoo-client-vpwkf
```

OS: Ubuntu 20.04
Kubernetes: v1.23.4
Docker: 20.10.7
Mondoo Operator 0.0.10
Mondoo Client: 5.29.2

**Comment by chris-rock** [comment]
Thank you again for reporting @czunker We retested it with the latest Mondoo Client 5.31.0 and the operator 0.2.0. When you upgrade to 0.2.0, it is best to uninstall the operator and reinstall the latest version since we switched from `mondoo-operator-system` to `mondoo-operator`. Please re-open if you are experiencing this issue with the latest version.

**Comment by czunker** [comment]
Thanks for the update.
It works now:

```
NAME                                                  READY   STATUS    RESTARTS   AGE
mondoo-client-75f487f669-jctm8                        1/1     Running   0          71m
mondoo-client-9jgmq                                   1/1     Running   0          73m
mondoo-client-br4l6                                   1/1     Running   0          73m
mondoo-client-mc79q                                   1/1     Running   0          73m
mondoo-client-msfh9                                   1/1     Running   0          73m
mondoo-client-qpd26                                   1/1     Running   0          73m
mondoo-client-z28gg                                   1/1     Running   0          73m
mondoo-client-zdsw9                                   1/1     Running   0          73m
mondoo-operator-controller-manager-556848b75d-29tl9   1/1     Running   0          73m
```
